# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.cache/wt [current_project]
set_property parent.project_path C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/sources_1/imports/new/temporary_counter.vhd
  C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/sources_1/imports/sources_1/new/overwrite.vhd
  C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/sources_1/imports/sources_1/imports/new/f_div_1.vhd
  C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/sources_1/imports/sources_1/new/btn_cleaner.vhd
  C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/sources_1/new/main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/constrs_1/imports/Desktop/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/pszemek/simple_counter_debouncer/simple_counter_debouncer.srcs/constrs_1/imports/Desktop/ZYBO_Master.xdc]


synth_design -top main -part xc7z010clg400-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
